From alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

ENV WORKSPACE /src/longhorn-tests

WORKDIR $WORKSPACE

RUN apk add --no-cache docker aws-cli jq bash grep

COPY [".", "$WORKSPACE"]
