apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: reboot-engine
  namespace: default
spec:
  # It can be delete/retain
  jobCleanUpPolicy: 'retain'
  engineState: 'active'
  chaosServiceAccount: ec2-terminate-by-id-sa
  components:
    runner:
      nodeSelector:
        kubernetes.io/hostname: engine-running-node
  experiments:
    - name: ec2-terminate-by-id
      spec:
        components:
          nodeSelector:
            kubernetes.io/hostname: engine-running-node
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'
            # set interval duration (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '180'
             # Instance ID of the target ec2 instance
             # Multiple IDs can also be provided as comma separated values ex: id1,id2
            - name: EC2_INSTANCE_ID
              value: instance-to-be-terminated
            # provide the region name of the instance
            - name: REGION
              value: 'us-east-1'
            # enable it if the target instance is a part of self-managed nodegroup.
            - name: MANAGED_NODEGROUP
              value: 'disable'