---
kind: pipeline
name: default-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  - main
  - v*

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: "flake8 check"
  pull: default
  image: rancher/dapper:v0.5.3
  commands:
  - dapper
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: "build longhorn-manager-test image"
  image: plugins/docker
  settings:
    dry_run: true
    build_args:
    - ARCH=amd64
    dockerfile: manager/integration/Dockerfile
    repo: longhornio/longhorn-manager-test
  when:
    event:
    - pull_request

- name: "publish longhorn-manager-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    custom_dns: 1.1.1.1
    dockerfile: manager/integration/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager-test
    tag: "${DRONE_BRANCH}-head-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - push

- name: "publish tagged longhorn-manager-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    custom_dns: 1.1.1.1
    dockerfile: manager/integration/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager-test
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: "build longhorn-e2e-test image"
  image: plugins/docker
  settings:
    dry_run: true
    build_args:
    - ARCH=amd64
    dockerfile: e2e/Dockerfile
    repo: longhornio/longhorn-e2e-test
  when:
    event:
    - pull_request

- name: "publish longhorn-e2e-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    custom_dns: 1.1.1.1
    dockerfile: e2e/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-e2e-test
    tag: "${DRONE_BRANCH}-head-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - push

- name: "publish tagged longhorn-e2e-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    custom_dns: 1.1.1.1
    dockerfile: e2e/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-e2e-test
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: default-arm64

platform:
  os: linux
  arch: arm64

trigger:
  branch:
  - master
  - main
  - v*

steps:
- name: fetch
  image: arm64v8/alpine
  commands:
  - apk add git
  - git fetch --tags

- name: "flake8 check"
  pull: default
  image: rancher/dapper:v0.5.3
  commands:
  - dapper
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: "build longhorn-manager-test image"
  image: plugins/docker
  settings:
    dry_run: true
    build_args:
    - ARCH=arm64
    dockerfile: manager/integration/Dockerfile
    repo: longhornio/longhorn-manager-test
  when:
    event:
    - pull_request

- name: "publish longhorn-manager-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    custom_dns: 1.1.1.1
    dockerfile: manager/integration/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager-test
    tag: "${DRONE_BRANCH}-head-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - push

- name: "publish tagged longhorn-manager-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    custom_dns: 1.1.1.1
    dockerfile: manager/integration/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager-test
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: "build longhorn-e2e-test image"
  image: plugins/docker
  settings:
    dry_run: true
    build_args:
    - ARCH=arm64
    dockerfile: e2e/Dockerfile
    repo: longhornio/longhorn-e2e-test
  when:
    event:
    - pull_request

- name: "publish longhorn-e2e-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    custom_dns: 1.1.1.1
    dockerfile: e2e/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-e2e-test
    tag: "${DRONE_BRANCH}-head-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - push

- name: "publish tagged longhorn-e2e-test image"
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    custom_dns: 1.1.1.1
    dockerfile: e2e/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-e2e-test
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  - main
  - v*

steps:
- name: "publish longhorn-manager-test manifest"
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "longhornio/longhorn-manager-test:${DRONE_BRANCH}-head"
    template: "longhornio/longhorn-manager-test:${DRONE_BRANCH}-head-ARCH"
  when:
    instance:
    - drone-publish.longhorn.io
    event:
    - push

- name: "publish tagged longhorn-manager-test manifest"
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "longhornio/longhorn-manager-test:${DRONE_TAG}"
    template: "longhornio/longhorn-manager-test:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.longhorn.io
    event:
    - tag

- name: "publish longhorn-e2e-test manifest"
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "longhornio/longhorn-e2e-test:${DRONE_BRANCH}-head"
    template: "longhornio/longhorn-e2e-test:${DRONE_BRANCH}-head-ARCH"
  when:
    instance:
    - drone-publish.longhorn.io
    event:
    - push

- name: "publish tagged longhorn-e2e-test manifest"
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
    target: "longhornio/longhorn-e2e-test:${DRONE_TAG}"
    template: "longhornio/longhorn-e2e-test:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.longhorn.io
    event:
    - tag

depends_on:
- default-amd64
- default-arm64
