---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags

- name: "flake8 check"
  pull: default
  image: rancher/dapper:1.11.2
  commands:
  - dapper
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: "publish longhorn-manager-test image"
  image: plugins/docker
  settings:
    custom_dns: 1.1.1.1
    context: manager/integration
    dockerfile: manager/integration/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager-test
    tag: v1.0.x
    username:
      from_secret: docker_username
  when:
    branch:
    - v1.0.x
    event:
    - push

- name: publish-tagged-image
  image: plugins/docker
  settings:
    custom_dns: 1.1.1.1
    context: manager/integration
    dockerfile: manager/integration/Dockerfile
    password:
      from_secret: docker_password
    repo: longhornio/longhorn-manager-test
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    branch:
    - v1.0.x
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
