FROM ubuntu:20.04@sha256:8feb4d8ca5354def3d8fce243717141ce31e2c428701f6682bd2fafe15388214

RUN apt-get update && \
    apt-get install -y wget build-essential python3 python3-dev python3-virtualenv vim && \
    rm -f /bin/sh && ln -s /bin/bash /bin/sh

ENV DAPPER_SOURCE /go/src/github.com/longhorn/longhorn-tests

WORKDIR ${DAPPER_SOURCE}

ENV VIRTUAL_ENV=${DAPPER_SOURCE}/manager/integration/.venv

RUN python3 -m virtualenv --python=/usr/bin/python3 ${VIRTUAL_ENV}

CMD ["./manager/integration/scripts/flake8-check.sh"]
