#!/bin/bash

inject_appco_env_vars() {
  local manifest="$1"
  # Injecting SUSE CA cert and run pdate-ca-certificates"
  if [[ "${LONGHORN_TEST_CLOUDPROVIDER}" == "harvester" ]]; then
    yq e -i 'select(.kind == "Pod").spec.containers[0].volumeMounts += {"name": "ca-cert-volume", "mountPath": "/etc/pki/trust/anchors", "readOnly": true}' "${manifest}"
    yq e -i 'select(.kind == "Pod").spec.volumes += {"name": "ca-cert-volume", "hostPath": {"path": "/etc/pki/trust/anchors", "type": "DirectoryOrCreate"}}' "${manifest}"
    yq e -i '( . | select(.kind=="Pod") | .spec.containers[0].lifecycle ).postStart = {"exec":{"command":["sh","-c","update-ca-certificates"]}}' "${manifest}"
    yq e -i 'select(.spec.containers[0] != null).spec.dnsPolicy = "None"' "${manifest}"
    yq e -i 'select(.spec.containers[0] != null).spec.dnsConfig.nameservers = ["10.113.53.53", "8.8.8.8", "1.1.1.1"]' "${manifest}"
  fi
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "REGISTRY_URL", "value": "'${REGISTRY_URL}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "AIR_GAP_INSTALLATION", "value": "'${AIR_GAP_INSTALLATION}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_UI_IMAGE", "value": "'${CUSTOM_LONGHORN_UI_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_SUPPORT_BUNDLE_IMAGE", "value": "'${CUSTOM_LONGHORN_SUPPORT_BUNDLE_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_CSI_ATTACHER_IMAGE", "value": "'${CUSTOM_LONGHORN_CSI_ATTACHER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_CSI_PROVISIONER_IMAGE", "value": "'${CUSTOM_LONGHORN_CSI_PROVISIONER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_CSI_NODE_DRIVER_REGISTRAR_IMAGE", "value": "'${CUSTOM_LONGHORN_CSI_NODE_DRIVER_REGISTRAR_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_CSI_RESIZER_IMAGE", "value": "'${CUSTOM_LONGHORN_CSI_RESIZER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_CSI_SNAPSHOTTER_IMAGE", "value": "'${CUSTOM_LONGHORN_CSI_SNAPSHOTTER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CUSTOM_LONGHORN_CSI_LIVENESSPROBE_IMAGE", "value": "'${CUSTOM_LONGHORN_CSI_LIVENESSPROBE_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_MANAGER_IMAGE", "value": "'${TRANSIENT_MANAGER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_ENGINE_IMAGE", "value": "'${TRANSIENT_ENGINE_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_INSTANCE_MANAGER_IMAGE", "value": "'${TRANSIENT_INSTANCE_MANAGER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_SHARE_MANAGER_IMAGE", "value": "'${TRANSIENT_SHARE_MANAGER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_BACKING_IMAGE_MANAGER_IMAGE", "value": "'${TRANSIENT_BACKING_IMAGE_MANAGER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_UI_IMAGE", "value": "'${TRANSIENT_UI_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_SUPPORT_BUNDLE_IMAGE", "value": "'${TRANSIENT_SUPPORT_BUNDLE_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_CSI_ATTACHER_IMAGE", "value": "'${TRANSIENT_CSI_ATTACHER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_CSI_PROVISIONER_IMAGE", "value": "'${TRANSIENT_CSI_PROVISIONER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_CSI_NODE_REGISTRAR_IMAGE", "value": "'${TRANSIENT_CSI_NODE_REGISTRAR_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_CSI_RESIZER_IMAGE", "value": "'${TRANSIENT_CSI_RESIZER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_CSI_SNAPSHOTTER_IMAGE", "value": "'${TRANSIENT_CSI_SNAPSHOTTER_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "TRANSIENT_CSI_LIVENESSPROBE_IMAGE", "value": "'${TRANSIENT_CSI_LIVENESSPROBE_IMAGE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "LONGHORN_TRANSIENT_VERSION_CHART_URI", "value": "'${LONGHORN_TRANSIENT_VERSION_CHART_URI}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "LONGHORN_STABLE_VERSION_CHART_URI", "value": "'${LONGHORN_STABLE_VERSION_CHART_URI}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "LONGHORN_CHART_URI", "value": "'${LONGHORN_CHART_URI}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "APPCO_LONGHORN_COMPONENT_IMAGE_PATH", "value": "'${APPCO_LONGHORN_COMPONENT_IMAGE_PATH}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "LONGHORN_VERSION", "value": "'${LONGHORN_VERSION}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "LONGHORN_NAMESPACE", "value": "'${LONGHORN_NAMESPACE}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "APPCO_USERNAME", "value": "'${APPCO_USERNAME}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "APPCO_PASSWORD", "value": "'${APPCO_PASSWORD}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "LONGHORN_COMPONENT_TAG", "value": "'${LONGHORN_COMPONENT_TAG}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CSI_ATTACHER_TAG", "value": "'${CSI_ATTACHER_TAG}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CSI_PROVISIONER_TAG", "value": "'${CSI_PROVISIONER_TAG}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CSI_RESIZER_TAG", "value": "'${CSI_RESIZER_TAG}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CSI_SNAPSHOTTER_TAG", "value": "'${CSI_SNAPSHOTTER_TAG}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CSI_LIVENESSPROBE_TAG", "value": "'${CSI_LIVENESSPROBE_TAG}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "CSI_REGISTRAR_TAG", "value": "'${CSI_REGISTRAR_TAG}'"}' "${manifest}"
  yq e -i 'select(.spec.containers[0] != null).spec.containers[0].env += {"name": "SUPPORT_BUNDLE_TAG", "value": "'${SUPPORT_BUNDLE_TAG}'"}' "${manifest}"
}
