apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeconfig-cluster-admin
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-cluster-admin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: kubeconfig-cluster-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeconfig-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeconfig-cluster-admin
  namespace: kube-system