apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test-nfs
  labels:
    app: longhorn-test-nfs
spec:
  containers:
  - name: longhorn-test-nfs-container
    image: janeczku/nfs-ganesha:latest
    imagePullPolicy: Always
    env:
    - name: EXPORT_ID
      value: "14"
    - name: EXPORT_PATH
      value: /opt/backupstore
    - name: PSEUDO_PATH
      value: /opt/backupstore
    command: ["bash", "-c", "mkdir -p /opt/backupstore && /opt/start_nfs.sh"]
    securityContext:
      capabilities:
        add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
---
kind: Service
apiVersion: v1
metadata:
  name: longhorn-test-nfs-svc
spec:
  selector:
    app: longhorn-test-nfs
  clusterIP: None
  ports:
  - name: notnecessary
    port: 1234
    targetPort: 1234
