apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - image: alpine/git
          imagePullPolicy: IfNotPresent
          name: sleep
          command: ['/bin/sh', '-c']
          args: ['while true;do date;sleep 5; done']
          volumeMounts:
            - name: pod-data
              mountPath: /data
      volumes:
        - name: pod-data
          persistentVolumeClaim:
            claimName: test-pvc