apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-rwo
  labels:
    app: test-deployment-rwo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment-rwo
  template:
    metadata:
      labels:
        app: test-deployment-rwo
    spec:
      containers:
        - image: busybox
          imagePullPolicy: IfNotPresent
          name: sleep
          args: ['/bin/sh', '-c', 'while true;do date;sleep 5; done']
          volumeMounts:
            - name: pod-data
              mountPath: /data
      volumes:
        - name: pod-data
          persistentVolumeClaim:
            claimName: test-rwo-pvc