apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    test.longhorn.io: e2e
spec:
  containers:
    - name: sleep
      image: public.ecr.aws/docker/library/busybox:1.34.1
      imagePullPolicy: IfNotPresent
      args: ["/bin/sh", "-c", "while true;do date;sleep 5; done"]
      volumeMounts:
        - name: pod-data
          mountPath: /data
  volumes:
    - name: pod-data
      persistentVolumeClaim:
        claimName: test-pvc
