apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    test.longhorn.io: e2e
spec:
  capacity:
    storage: 3221225472
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: test-pv
