apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rwo-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi