apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rwx-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi