---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset
  namespace: default
  labels:
    test.longhorn.io: e2e
spec:
  selector:
    matchLabels:
      app: test-statefulset
  serviceName: test-statefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: test-statefulset
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
      containers:
      - image: alpine/git
        imagePullPolicy: IfNotPresent
        name: sleep
        command: ['/bin/sh', '-c']
        args: ['while true;do date;sleep 5; done']
        volumeMounts:
        - name: pod-data
          mountPath: "/data"
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
  - metadata:
      name: pod-data
      labels:
        test.longhorn.io: e2e
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 3221225472  #3Gi
