---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-test-nfs-options
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '2'
  staleReplicaTimeout: '30'
  nfsOptions: "vers=4.2,noresvport,timeo=450,retrans=8"
reclaimPolicy: Delete
