apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: @STS_NAME@
spec:
  replicas: 0
  serviceName: @STS_NAME@
  selector:
    matchLabels:
      app: @STS_NAME@
  template:
    metadata:
      labels:
        app: @STS_NAME@
    spec:
      nodeName: @NODE_NAME@
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: '@STS_NAME@'
        image: 'phanle1010/ubuntu:fio'
        command: ["/bin/bash"]
        args: ["-c", "while :; do fio --name=simulate-workload-io --ioengine=libaio --direct=1 --readwrite=randrw --bs=128k --size=3G --io_size=2G --filename=/mnt/@STS_NAME@/fio_test_file --iodepth=4 --rwmixread=75; sync; sleep 15; done"]
        livenessProbe:
          exec:
            command:
              - ls
              - /mnt/@STS_NAME@
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: @STS_NAME@
          mountPath: /mnt/@STS_NAME@
  volumeClaimTemplates:
  - metadata:
      name: @STS_NAME@
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 4Gi
