def imageName = "${JOB_BASE_NAME}-${env.BUILD_NUMBER}"
def summary
def BUILD_TRIGGER_BY = "\n${currentBuild.getBuildCauses()[0].shortDescription}"

node {

	if(params.SEND_SLACK_NOTIFICATION){
		notifyBuild('STARTED', BUILD_TRIGGER_BY, params.NOTIFY_SLACK_CHANNEL)
	}

    checkout scm

    withCredentials([
        usernamePassword(credentialsId: 'DOCKER_CREDS', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME'),
        usernamePassword(credentialsId: 'AWS_CREDS', passwordVariable: 'AWS_SECRET_KEY', usernameVariable: 'AWS_ACCESS_KEY'),
        string(credentialsId: 'AWS_DEFAULT_REGION', variable: 'AWS_DEFAULT_REGION'),
        string(credentialsId: 'AWS_PRIVATE_ECR', variable: 'AWS_PRIVATE_ECR'),
        file(credentialsId: 'SUSE_INTERNAL_CA', variable: 'CA_CERT_PATH'),
        usernamePassword(credentialsId: 'APPCO_CREDS', passwordVariable: 'APPCO_PASSWORD', usernameVariable: 'APPCO_USERNAME'),
    ]) {
        stage('build') {

            sh "cp ${CA_CERT_PATH} ./SUSE_Trust_Root.crt"
            sh "mirror_csi_images/scripts/build.sh"

            sh """ docker run -itd --name ${JOB_BASE_NAME}-${BUILD_NUMBER} \
                                   --env DOCKER_USERNAME="${DOCKER_USERNAME}" \
                                   --env DOCKER_PASSWORD="${DOCKER_PASSWORD}" \
                                   --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY} \
                                   --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY} \
                                   --env AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
                                   --env AWS_PRIVATE_ECR=${AWS_PRIVATE_ECR} \
                                   --env LONGHORN_IMAGES_FILE_URL=${LONGHORN_IMAGES_FILE_URL} \
                                   --env CSI_IMAGES=${CSI_IMAGES} \
                                   --env APPCO_USERNAME=${APPCO_USERNAME} \
                                   --env APPCO_PASSWORD=${APPCO_PASSWORD} \
                                   --dns=10.113.53.53 \
                                   --dns=10.113.53.54 \
                                   ${imageName}
            """
        }

        try {

            stage ('tag and publish') {
                sh  " docker exec ${JOB_BASE_NAME}-${BUILD_NUMBER} ${TF_VAR_tf_workspace}/scripts/publish.sh"
            }

        } catch(e) {
            currentBuild.result = "FAILED"
            throw e
        } finally {
            stage('releasing resources') {

                sh "docker stop ${JOB_BASE_NAME}-${BUILD_NUMBER}"
                sh "docker rm -v ${JOB_BASE_NAME}-${BUILD_NUMBER}"
                sh "docker rmi ${imageName}"

				if(params.SEND_SLACK_NOTIFICATION){
					notifyBuild(currentBuild.result, "", params.NOTIFY_SLACK_CHANNEL)
				}
            }
        }
    }
}


def notifyBuild(String buildStatus = 'STARTED', String summary_msg, String slack_channel) {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'

  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def subject = "${buildStatus}: Job '${env.JOB_BASE_NAME} [${env.BUILD_NUMBER}]'"
  def summary = "${subject} (${env.BUILD_URL})" + summary_msg

  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (buildStatus == 'SUCCESSFUL') {
    color = 'GREEN'
    colorCode = '#00FF00'
  } else {
    color = 'RED'
    colorCode = '#FF0000'
  }

  // Send notifications
  slackSend (color: colorCode, message: summary, channel: slack_channel,  tokenCredentialId: 'longhorn-tests-slack-token')
}
