def imageName = "${JOB_BASE_NAME}-${env.BUILD_NUMBER}"

node {
    notifyBuild('STARTED')

    checkout scm

    withCredentials([
        usernamePassword(credentialsId: 'APPCO_CREDS', passwordVariable: 'APPCO_PASSWORD', usernameVariable: 'APPCO_USERNAME'),
        file(credentialsId: 'SUSE_INTERNAL_CA', variable: 'CA_CERT_PATH'),
    ]) {
        stage('build') {
            sh "cp ${CA_CERT_PATH} ./SUSE_Trust_Root.crt"
            sh "secscan/scripts/build.sh"
            sh """docker run -itd \
                             --name ${imageName} \
                             -v /var/run/docker.sock:/var/run/docker.sock \
                             --env TF_VAR_tf_workspace=${TF_VAR_tf_workspace} \
                             --env SEVERITY=${TF_VAR_SEVERITY} \
                             --env LONGHORN_VERSION=${TF_VAR_LONGHORN_VERSION} \
                             --env APPCO_USERNAME=${APPCO_USERNAME} \
                             --env APPCO_PASSWORD=${APPCO_PASSWORD} \
                             --dns=10.113.53.53 \
                             --dns=10.113.53.54 \
                             ${imageName}
            """
        }

        try {
            stage ('scan images') {
                sh "docker exec ${imageName} ${TF_VAR_tf_workspace}/scripts/secscan.sh"
            }

            stage ('report generation') {
                sh "docker cp ${imageName}:/junit-reports ."
                def summary = junit allowEmptyResults: true, testResults: "junit-reports/*.xml"
            }

        } catch(e) {
            currentBuild.result = "FAILED"
            throw e
        } finally {
            stage('releasing resources') {
                sh "docker stop ${imageName}"
                sh "docker rm -v ${imageName}"
                sh "docker rmi ${imageName}"
                notifyBuild(currentBuild.result)
            }
        }
    }
}


def notifyBuild(String buildStatus = 'STARTED') {
  // build status of null means successful
  buildStatus =  buildStatus ?: 'SUCCESSFUL'

  // Default values
  def colorName = 'RED'
  def colorCode = '#FF0000'
  def subject = "${buildStatus}: Job '${env.JOB_BASE_NAME} [${env.BUILD_NUMBER}]'"
  def summary = "${subject} (${env.BUILD_URL})"

  // Override default values based on build status
  if (buildStatus == 'STARTED') {
    color = 'YELLOW'
    colorCode = '#FFFF00'
  } else if (buildStatus == 'SUCCESSFUL') {
    color = 'GREEN'
    colorCode = '#00FF00'
  } else {
    color = 'RED'
    colorCode = '#FF0000'
    // Send failed notifications
    slackSend (color: colorCode, message: summary,  tokenCredentialId: 'longhorn-tests-slack-token')
  }

  // Send notifications
  slackSend (color: colorCode, message: summary, tokenCredentialId: 'longhorn-tests-slack-token')
}
