NODE_STRESS_CPU_LOAD_PERCENTAGE = 100
NODE_STRESS_MEM_LOAD_PERCENTAGE = 100
NODE_STRESS_MEM_VM_WORKERS = 1
NODE_STRESS_TIMEOUT_SECOND = 60 * 60  # 1 hour

STRESS_HELPER_LABEL = "longhorn-stress-helper"
STRESS_HELPER_POD_NAME_PREFIX = "longhorn-stress-helper-"
