name: Qase Sync

on:
  push:
    branches:
      - master

jobs:
  qase-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Qase Sync
        uses: longhorn/bot/qase-sync-action@937b18e87b98f77e382bde2aaeb0c602e8841d85 # master
        with:
          project-code: LH
          token: ${{ secrets.QASE_TOKEN }}
